In [1]:
# A manual implementation of a finite difference method
# Theo Wecker 2019 @ CSU
import numpy as np
import scipy.linalg as linalg

#define the exact function of the solution
def f(x):
    c = np.sinh(10)
    return (c*np.sinh(2*x))


#defining the system of equations
A = np.array([[-2.25, 1, 0],
 [1, -2.25, 1],
 [0, 1, -2.25]])

#constants vector
B = np.array([0, 0, -5])

#inversion of the system of equations
Ain = np.linalg.inv(A)

#solving for the y-vector
y = Ain @ B

print(A)
print(B)
print('\n')
print(Ain)
print('\n')
print(y)

#percent error

percent_y1 = y[0]/f(.25)*100
print('\n')
print(percent_y1)

percent_y2 = y[1]/f(.5)*100
print(percent_y2)

percent_y3 = y[2]/f(.75)*100
print(percent_y3)
print('\n\n\n')

###   PART 2 w/ 10 interior points   ###

#defining the system of equations
A2 = np.array([
 [-2.033, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, -2.033, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, -2.033, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, -2.033, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, -2.033, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, -2.033, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, -2.033, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, -2.033, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, -2.033, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, -2.033]
               ])

#constants vector
B2 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, -5])

#inversion of the system of equations
Ain2 = np.linalg.inv(A2)

#solving for the y-vector
y2 = Ain2 @ B2

print(A2)
print('\n')
print(B2)
print('\n')
print(Ain2)
print('\n')
print(y2)

[[-2.25  1.    0.  ]
 [ 1.   -2.25  1.  ]
 [ 0.    1.   -2.25]]
[ 0  0 -5]


[[-0.58956916 -0.32653061 -0.14512472]
 [-0.32653061 -0.73469388 -0.32653061]
 [-0.14512472 -0.32653061 -0.58956916]]


[0.72562358 1.63265306 2.9478458 ]


0.012643852060146947
0.012614407619695017
0.01257063674312394




[[-2.033  1.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 1.    -2.033  1.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     1.    -2.033  1.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     1.    -2.033  1.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     1.    -2.033  1.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     1.    -2.033  1.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     1.    -2.033  1.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.     1.    -2.033  1.     0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.     1.    -2.033  1.   ]
 [ 0.     0.     0.     0.     0.     0.   